/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/s3-workflows/wrangler.jsonc --include-runtime=false workers/s3-workflows/worker-configuration.d.ts` (hash: d36b86311b868fcbbd28ff52783ecdd1)
interface __BaseEnv_Env {
	SESSIONS: KVNamespace;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	SESSION_DOMAIN: string;
	S3_SYNC_INDEX: DurableObjectNamespace<import("./src/index").S3SyncIndex>;
	S3_BACKFILL_WORKFLOW: Workflow<Parameters<import("./src/index").S3BackfillWorkflow['run']>[0]['payload']>;
	S3_MIRROR_WORKFLOW: Workflow<Parameters<import("./src/index").S3MirrorWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "S3SyncIndex";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "SESSION_DOMAIN">> {}
}
